import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { toast } from '@/components/ui/use-toast';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import { useProject } from '@/context/ProjectContext';
import { isDevelopmentMode } from '@/utils/devMode';
import { VisionScoring } from '@/utils/visionApi';
import { calculateOpportunityScore } from '@/utils/scoringCalculation';
import { scoreImage } from '@/services/imageScoring';
import { ModelComparisonResultWithCache } from '@/types/scoring';
import { useScoringConfig } from '@/hooks/useScoringConfig';
